### ISSUE TITLE
Running make fails when building examples/test_dctvideohash.cpp

### ISSUE THREAD

**Issue by chalford** [aetilius/pHash#13]
I used `ccmake` to configure the Makefiles, setting `WITH_VIDEO_HASH` to `ON`. Subsequently building with `make`, the process throws an error when trying to build `examples/test_dctvideohash.cpp`.

### Error details

```
/path/to/phash/examples/test_dctvideohash.cpp:44:25: error: use of undeclared identifier
      'ph_dct_videohash'; did you mean 'ph_dct_imagehash'?
        hashes[i - 1] = ph_dct_videohash(argv[i], lengths[i - 1]);
                        ^~~~~~~~~~~~~~~~
                        ph_dct_imagehash
/usr/local/include/pHash.h:229:5: note: 'ph_dct_imagehash' declared here
int ph_dct_imagehash(const char* file,ulong64 &hash);
    ^
```

### Workaround

Looking in `pHash.h`, I can see `#ifdef` conditionally wrapping the signature for `ph_dct_videohash`. I used `make -n` to find the `c++` command that was being used to compile the file that was throwing an error. I added `-D HAVE_VIDEO_HASH=1` to that command, and ran it, which successfully compiled. I then continued to run `make` and `make install` which completed successfully.

I'm not sure if the problem here is my configuration, my environment (Mac OS 10.14), or something else.

**Comment by starkdg** [comment]
Thanks.  There's a new branch in v1.0.0 with cmake build completely redone.  The win32 is left unchanged though, as that's not being maintained. However, it's there just in case.  

https://github.com/aetilius/pHash/tree/r1.0.0

**Comment by eklinger** [comment]
Proper way to build is:
cmake -DWITH_AUDIO_HASH=1 -DWITH_VIDEO_HASH=1 ..
