### ISSUE TITLE
Build fails due to missing libraries.

### ISSUE THREAD

**Issue by bbhopesh** [aetilius/pHash#5]
Hi, I am trying to do a build and getting below error. It could not find `jpeglib.h`. Please see snapshot.

![image](https://user-images.githubusercontent.com/8807496/63828292-cbf9f700-c91a-11e9-8dbd-80b346084f1d.png)

**Comment by bbhopesh** [comment]
I am able to successfully build now but still couldn't use it. It seems like build process is not generating all the binaries that it is supposed to do. Moreover, `make install` is failing with missing `pHash.h`. 

It will be great if you could share the build process in detail. Thanks a lot.

**Comment by aetilius** [comment]
Hello,
Can you please share which binaries you are missing? Header installation has been fixed. Thank you for reporting it.

**Comment by bbhopesh** [comment]
Basically I am not sure how to use it after compilation. I am looking for binaries like `imghash`(found this name on other similarly looking repos) and similar binaries that I can use to hash videos, audio etc. However, compilation only generates `Test*` binaries
