### ISSUE TITLE
./configure fails due to ffmpeg version

### ISSUE THREAD

**Issue by Avagenzo** [aetilius/pHash#6]
Output on Ubuntu 18.04:

```
*** Configuring image hash ***

checking CImg.h usability... no
checking CImg.h presence... no
checking for CImg.h... no
checking whether CImg.h is in the current or src directory.... no

*** Configuring video Hash ***

checking whether FFmpeg is present... checking for avcodec_alloc_frame in -lavcodec... no
configure: error:

*** libavcodec not found.
You need FFmpeg. Get it at <http://ffmpeg.org/>
```

Seems like its not compatible to ffmpeg version:
[(https://stackoverflow.com/questions/30107520/error-installing-phash-on-ubuntu)]

FFmpeg is definitely installed under /usr/local/bin. Do you know how to fix this?

**Comment by Avagenzo** [comment]
Or could you at least mention the version of ffmpeg PHash is compatible with ?

**Comment by aetilius** [comment]
It seems like you are using the download from the website. If you check out from git you can use cmake to build. It will work with the latest FFmpeg. But you need the FFmpeg development libraries not the binary.

**Comment by diegopamio** [comment]
I'm having the same issue, but I cannot see any ./configure in the cloned repo.
